// GENERATED by pipeline/pipeline.py — the deterministic core.
// Every figure in the application renders from this module and nowhere else.
// No model was involved in producing any value in this file.
export const DATA = {
 "totals": {
  "fy2022": {
   "tier": "AGGREGATED",
   "value": 29535369459.65,
   "method": "Sum of Amount across all FY 2022 payment rows",
   "sources": [
    {
     "sheet": "FY 2022",
     "rows_contributing": 451029
    }
   ]
  },
  "fy2023": {
   "tier": "AGGREGATED",
   "value": 33711812451.38,
   "method": "Sum of Amount across all FY 2023 payment rows",
   "sources": [
    {
     "sheet": "FY 2023",
     "rows_contributing": 484824
    }
   ]
  },
  "yoy": {
   "tier": "TEMPORAL",
   "value": 4176442991.73,
   "method": "FY2023 total minus FY2022 total",
   "current": {
    "tier": "AGGREGATED",
    "value": 33711812451.38,
    "method": "Sum of Amount across all FY 2023 payment rows",
    "sources": [
     {
      "sheet": "FY 2023",
      "rows_contributing": 484824
     }
    ]
   },
   "prior": {
    "tier": "AGGREGATED",
    "value": 29535369459.65,
    "method": "Sum of Amount across all FY 2022 payment rows",
    "sources": [
     {
      "sheet": "FY 2022",
      "rows_contributing": 451029
     }
    ]
   }
  }
 },
 "agencies": [
  {
   "name": "Health Care Authority",
   "fy2022": 13124865771.0,
   "fy2023": 14946888936.3,
   "delta": 1822023165.3,
   "pct": 13.9,
   "rows": {
    "2022": 41992,
    "2023": 43060
   }
  },
  {
   "name": "Social and Health Services",
   "fy2022": 6023569856.74,
   "fy2023": 7443047723.65,
   "delta": 1419477866.91,
   "pct": 23.6,
   "rows": {
    "2022": 79188,
    "2023": 93181
   }
  },
  {
   "name": "Transportation",
   "fy2022": 1752935701.7,
   "fy2023": 2312104970.51,
   "delta": 559169268.81,
   "pct": 31.9,
   "rows": {
    "2022": 20714,
    "2023": 25744
   }
  },
  {
   "name": "Commerce",
   "fy2022": 1415870737.19,
   "fy2023": 1842871707.79,
   "delta": 427000970.6,
   "pct": 30.2,
   "rows": {
    "2022": 8358,
    "2023": 12131
   }
  },
  {
   "name": "Children, Youth, and Families",
   "fy2022": 1342719953.97,
   "fy2023": 1297256390.62,
   "delta": -45463563.35,
   "pct": -3.4,
   "rows": {
    "2022": 105168,
    "2023": 61510
   }
  },
  {
   "name": "Health",
   "fy2022": 1447472094.34,
   "fy2023": 921991410.22,
   "delta": -525480684.12,
   "pct": -36.3,
   "rows": {
    "2022": 12158,
    "2023": 18672
   }
  },
  {
   "name": "Public Schools",
   "fy2022": 912194950.7,
   "fy2023": 714569423.75,
   "delta": -197625526.95,
   "pct": -21.7,
   "rows": {
    "2022": 10078,
    "2023": 11540
   }
  },
  {
   "name": "Military Department",
   "fy2022": 403235659.78,
   "fy2023": 511891173.06,
   "delta": 108655513.28,
   "pct": 26.9,
   "rows": {
    "2022": 4142,
    "2023": 5023
   }
  },
  {
   "name": "Ecology",
   "fy2022": 434597312.24,
   "fy2023": 472276826.16,
   "delta": 37679513.92,
   "pct": 8.7,
   "rows": {
    "2022": 8000,
    "2023": 11071
   }
  },
  {
   "name": "Corrections",
   "fy2022": 400320077.82,
   "fy2023": 454787389.0,
   "delta": 54467311.18,
   "pct": 13.6,
   "rows": {
    "2022": 14212,
    "2023": 17886
   }
  },
  {
   "name": "Natural Resources",
   "fy2022": 208864052.48,
   "fy2023": 271798678.44,
   "delta": 62934625.96,
   "pct": 30.1,
   "rows": {
    "2022": 11594,
    "2023": 15080
   }
  },
  {
   "name": "Enterprise Services",
   "fy2022": 164151709.25,
   "fy2023": 245960570.18,
   "delta": 81808860.93,
   "pct": 49.8,
   "rows": {
    "2022": 4809,
    "2023": 5163
   }
  },
  {
   "name": "Fish and Wildlife",
   "fy2022": 143492737.97,
   "fy2023": 194509167.73,
   "delta": 51016429.76,
   "pct": 35.6,
   "rows": {
    "2022": 13675,
    "2023": 17220
   }
  },
  {
   "name": "Recreation and Conservation Office",
   "fy2022": 166325166.45,
   "fy2023": 193750227.86,
   "delta": 27425061.41,
   "pct": 16.5,
   "rows": {
    "2022": 2213,
    "2023": 2854
   }
  },
  {
   "name": "Labor and Industries",
   "fy2022": 163998211.4,
   "fy2023": 178309579.28,
   "delta": 14311367.88,
   "pct": 8.7,
   "rows": {
    "2022": 9278,
    "2023": 12514
   }
  },
  {
   "name": "Agriculture",
   "fy2022": 105424785.65,
   "fy2023": 150332986.2,
   "delta": 44908200.55,
   "pct": 42.6,
   "rows": {
    "2022": 7021,
    "2023": 8602
   }
  },
  {
   "name": "State Patrol",
   "fy2022": 112401943.25,
   "fy2023": 139770310.94,
   "delta": 27368367.69,
   "pct": 24.3,
   "rows": {
    "2022": 9945,
    "2023": 10841
   }
  },
  {
   "name": "Consolidated Technology Services",
   "fy2022": 124543839.99,
   "fy2023": 139317566.15,
   "delta": 14773726.16,
   "pct": 11.9,
   "rows": {
    "2022": 1500,
    "2023": 1890
   }
  },
  {
   "name": "Employment Security Department",
   "fy2022": 135134357.34,
   "fy2023": 126502522.81,
   "delta": -8631834.53,
   "pct": -6.4,
   "rows": {
    "2022": 4841,
    "2023": 5913
   }
  },
  {
   "name": "Licensing",
   "fy2022": 72059180.95,
   "fy2023": 92958069.77,
   "delta": 20898888.82,
   "pct": 29.0,
   "rows": {
    "2022": 4090,
    "2023": 4738
   }
  },
  {
   "name": "State Parks and Recreation Comm",
   "fy2022": 65710862.82,
   "fy2023": 86613210.04,
   "delta": 20902347.22,
   "pct": 31.8,
   "rows": {
    "2022": 5183,
    "2023": 5925
   }
  },
  {
   "name": "Transportation Improvement Board",
   "fy2022": 72071673.52,
   "fy2023": 74578821.38,
   "delta": 2507147.86,
   "pct": 3.5,
   "rows": {
    "2022": 937,
    "2023": 1098
   }
  },
  {
   "name": "Financial Management",
   "fy2022": 71280506.63,
   "fy2023": 74417256.12,
   "delta": 3136749.49,
   "pct": 4.4,
   "rows": {
    "2022": 1858,
    "2023": 2430
   }
  },
  {
   "name": "Administrative Office of the Courts",
   "fy2022": 52999367.09,
   "fy2023": 68912024.63,
   "delta": 15912657.54,
   "pct": 30.0,
   "rows": {
    "2022": 3843,
    "2023": 4880
   }
  },
  {
   "name": "Student Achievement Council",
   "fy2022": 39018467.77,
   "fy2023": 68265971.13,
   "delta": 29247503.36,
   "pct": 75.0,
   "rows": {
    "2022": 1797,
    "2023": 2389
   }
  },
  {
   "name": "Attorney General",
   "fy2022": 56661756.48,
   "fy2023": 58604952.34,
   "delta": 1943195.86,
   "pct": 3.4,
   "rows": {
    "2022": 4796,
    "2023": 6744
   }
  },
  {
   "name": "Public Defense",
   "fy2022": 59827610.24,
   "fy2023": 57554868.86,
   "delta": -2272741.38,
   "pct": -3.8,
   "rows": {
    "2022": 4522,
    "2023": 5436
   }
  },
  {
   "name": "Secretary of State",
   "fy2022": 29648561.0,
   "fy2023": 54847871.73,
   "delta": 25199310.73,
   "pct": 85.0,
   "rows": {
    "2022": 1720,
    "2023": 2638
   }
  },
  {
   "name": "Civil Legal Aid",
   "fy2022": 44982402.57,
   "fy2023": 52593477.6,
   "delta": 7611075.03,
   "pct": 16.9,
   "rows": {
    "2022": 1085,
    "2023": 1255
   }
  },
  {
   "name": "Revenue",
   "fy2022": 45314470.73,
   "fy2023": 44930407.11,
   "delta": -384063.62,
   "pct": -0.8,
   "rows": {
    "2022": 4549,
    "2023": 6501
   }
  },
  {
   "name": "Veterans' Affairs",
   "fy2022": 34722703.7,
   "fy2023": 42623453.0,
   "delta": 7900749.3,
   "pct": 22.8,
   "rows": {
    "2022": 4024,
    "2023": 4583
   }
  },
  {
   "name": "Criminal Justice Training Cmsn",
   "fy2022": 31938302.64,
   "fy2023": 39974337.18,
   "delta": 8036034.54,
   "pct": 25.2,
   "rows": {
    "2022": 2377,
    "2023": 2572
   }
  },
  {
   "name": "Conservation Commission",
   "fy2022": 20658532.09,
   "fy2023": 31646045.02,
   "delta": 10987512.93,
   "pct": 53.2,
   "rows": {
    "2022": 1096,
    "2023": 1272
   }
  },
  {
   "name": "Workforce Trng & Educ Coord Board",
   "fy2022": 21323578.78,
   "fy2023": 22787072.06,
   "delta": 1463493.28,
   "pct": 6.9,
   "rows": {
    "2022": 484,
    "2023": 817
   }
  },
  {
   "name": "Retirement Systems",
   "fy2022": 17141750.46,
   "fy2023": 20777808.59,
   "delta": 3636058.13,
   "pct": 21.2,
   "rows": {
    "2022": 1009,
    "2023": 1183
   }
  },
  {
   "name": "Liquor and Cannabis Board",
   "fy2022": 14363144.0,
   "fy2023": 19764161.88,
   "delta": 5401017.88,
   "pct": 37.6,
   "rows": {
    "2022": 1711,
    "2023": 2014
   }
  },
  {
   "name": "County Road Administration Board",
   "fy2022": 22356971.0,
   "fy2023": 15712149.91,
   "delta": -6644821.09,
   "pct": -29.7,
   "rows": {
    "2022": 621,
    "2023": 633
   }
  },
  {
   "name": "Traffic Safety Commission",
   "fy2022": 9047097.52,
   "fy2023": 13560398.28,
   "delta": 4513300.76,
   "pct": 49.9,
   "rows": {
    "2022": 1528,
    "2023": 2227
   }
  },
  {
   "name": "Utilities and Transportation Cmsn",
   "fy2022": 15459356.01,
   "fy2023": 12575360.51,
   "delta": -2883995.5,
   "pct": -18.7,
   "rows": {
    "2022": 1088,
    "2023": 1148
   }
  },
  {
   "name": "School for the Blind",
   "fy2022": 4246103.62,
   "fy2023": 11438291.32,
   "delta": 7192187.7,
   "pct": 169.4,
   "rows": {
    "2022": 1077,
    "2023": 1302
   }
  },
  {
   "name": "Arts Commission",
   "fy2022": 5945783.26,
   "fy2023": 11392266.0,
   "delta": 5446482.74,
   "pct": 91.6,
   "rows": {
    "2022": 1212,
    "2023": 1539
   }
  },
  {
   "name": "Insurance Commissioner",
   "fy2022": 8384004.55,
   "fy2023": 10503204.43,
   "delta": 2119199.88,
   "pct": 25.3,
   "rows": {
    "2022": 1513,
    "2023": 1945
   }
  },
  {
   "name": "Auditor",
   "fy2022": 8154354.41,
   "fy2023": 10252877.59,
   "delta": 2098523.18,
   "pct": 25.7,
   "rows": {
    "2022": 1610,
    "2023": 2869
   }
  },
  {
   "name": "Deaf and Hard of Hearing Youth",
   "fy2022": 8833859.74,
   "fy2023": 10005874.69,
   "delta": 1172014.95,
   "pct": 13.3,
   "rows": {
    "2022": 1360,
    "2023": 1666
   }
  },
  {
   "name": "Puget Sound Partnership",
   "fy2022": 7064416.23,
   "fy2023": 9705945.99,
   "delta": 2641529.76,
   "pct": 37.4,
   "rows": {
    "2022": 620,
    "2023": 971
   }
  },
  {
   "name": "Services for the Blind",
   "fy2022": 7740341.09,
   "fy2023": 9653356.31,
   "delta": 1913015.22,
   "pct": 24.7,
   "rows": {
    "2022": 1971,
    "2023": 2297
   }
  },
  {
   "name": "Historical Society",
   "fy2022": 6329228.37,
   "fy2023": 8225242.81,
   "delta": 1896014.44,
   "pct": 30.0,
   "rows": {
    "2022": 605,
    "2023": 724
   }
  },
  {
   "name": "Administrative Hearings",
   "fy2022": 5264228.53,
   "fy2023": 7765651.39,
   "delta": 2501422.86,
   "pct": 47.5,
   "rows": {
    "2022": 835,
    "2023": 971
   }
  },
  {
   "name": "Joint Legislative Systems Committee",
   "fy2022": 4895471.55,
   "fy2023": 7631586.56,
   "delta": 2736115.01,
   "pct": 55.9,
   "rows": {
    "2022": 702,
    "2023": 831
   }
  },
  {
   "name": "State Investment Board",
   "fy2022": 5768067.89,
   "fy2023": 7624070.18,
   "delta": 1856002.29,
   "pct": 32.2,
   "rows": {
    "2022": 762,
    "2023": 1443
   }
  },
  {
   "name": "Financial Institutions",
   "fy2022": 6460866.54,
   "fy2023": 7447643.75,
   "delta": 986777.21,
   "pct": 15.3,
   "rows": {
    "2022": 999,
    "2023": 2215
   }
  },
  {
   "name": "House of Representatives",
   "fy2022": 4649430.82,
   "fy2023": 6445919.94,
   "delta": 1796489.12,
   "pct": 38.6,
   "rows": {
    "2022": 1872,
    "2023": 3363
   }
  },
  {
   "name": "Industrial Insurance Appeals",
   "fy2022": 5807294.63,
   "fy2023": 5976804.04,
   "delta": 169509.41,
   "pct": 2.9,
   "rows": {
    "2022": 1245,
    "2023": 1391
   }
  },
  {
   "name": "Governor",
   "fy2022": 4327802.74,
   "fy2023": 5577436.41,
   "delta": 1249633.67,
   "pct": 28.9,
   "rows": {
    "2022": 879,
    "2023": 1137
   }
  },
  {
   "name": "Senate",
   "fy2022": 3701832.88,
   "fy2023": 4841815.15,
   "delta": 1139982.27,
   "pct": 30.8,
   "rows": {
    "2022": 1443,
    "2023": 2130
   }
  },
  {
   "name": "Gambling Commission",
   "fy2022": 3985934.04,
   "fy2023": 4241565.38,
   "delta": 255631.34,
   "pct": 6.4,
   "rows": {
    "2022": 1590,
    "2023": 1651
   }
  },
  {
   "name": "Freight Mobility Strategic Investmt",
   "fy2022": 2096351.12,
   "fy2023": 4131191.11,
   "delta": 2034839.99,
   "pct": 97.1,
   "rows": {
    "2022": 282,
    "2023": 286
   }
  },
  {
   "name": "Archaeology & Historic Preservation",
   "fy2022": 7428633.78,
   "fy2023": 4120990.67,
   "delta": -3307643.11,
   "pct": -44.5,
   "rows": {
    "2022": 376,
    "2023": 537
   }
  },
  {
   "name": "Court of Appeals",
   "fy2022": 3490986.02,
   "fy2023": 3864058.56,
   "delta": 373072.54,
   "pct": 10.7,
   "rows": {
    "2022": 653,
    "2023": 763
   }
  },
  {
   "name": "Independent Investigations",
   "fy2022": 1536419.53,
   "fy2023": 3588791.67,
   "delta": 2052372.14,
   "pct": 133.6,
   "rows": {
    "2022": 69,
    "2023": 394
   }
  },
  {
   "name": "Energy Facility Site Eval Council",
   "fy2022": 0.0,
   "fy2023": 3587869.97,
   "delta": 3587869.97,
   "pct": null,
   "rows": {
    "2022": 0,
    "2023": 297
   }
  },
  {
   "name": "Treasurer",
   "fy2022": 2297974.04,
   "fy2023": 3266199.27,
   "delta": 968225.23,
   "pct": 42.1,
   "rows": {
    "2022": 529,
    "2023": 669
   }
  },
  {
   "name": "Lottery Commission",
   "fy2022": 3084216.16,
   "fy2023": 2985851.56,
   "delta": -98364.6,
   "pct": -3.2,
   "rows": {
    "2022": 800,
    "2023": 783
   }
  },
  {
   "name": "Pilotage Commissioners",
   "fy2022": 2616719.61,
   "fy2023": 2439875.95,
   "delta": -176843.66,
   "pct": -6.8,
   "rows": {
    "2022": 281,
    "2023": 238
   }
  },
  {
   "name": "Minority & Women's Business Enterp",
   "fy2022": 1430089.39,
   "fy2023": 2357912.32,
   "delta": 927822.93,
   "pct": 64.9,
   "rows": {
    "2022": 362,
    "2023": 400
   }
  },
  {
   "name": "Eastern WA State Historical Society",
   "fy2022": 3131766.74,
   "fy2023": 2245553.32,
   "delta": -886213.42,
   "pct": -28.3,
   "rows": {
    "2022": 463,
    "2023": 468
   }
  },
  {
   "name": "Public Disclosure Commission",
   "fy2022": 2100469.37,
   "fy2023": 1842714.96,
   "delta": -257754.41,
   "pct": -12.3,
   "rows": {
    "2022": 601,
    "2023": 525
   }
  },
  {
   "name": "Transportation Commission",
   "fy2022": 419405.03,
   "fy2023": 1753883.9,
   "delta": 1334478.87,
   "pct": 318.2,
   "rows": {
    "2022": 255,
    "2023": 380
   }
  },
  {
   "name": "Joint Leg Audit & Review Committee",
   "fy2022": 1058354.58,
   "fy2023": 1520559.83,
   "delta": 462205.25,
   "pct": 43.7,
   "rows": {
    "2022": 234,
    "2023": 355
   }
  },
  {
   "name": "Bond Retirement and Interest",
   "fy2022": 1216473.4,
   "fy2023": 1506703.2,
   "delta": 290229.8,
   "pct": 23.9,
   "rows": {
    "2022": 64,
    "2023": 65
   }
  },
  {
   "name": "Joint Transportation Committee",
   "fy2022": 1121438.57,
   "fy2023": 1491641.75,
   "delta": 370203.18,
   "pct": 33.0,
   "rows": {
    "2022": 238,
    "2023": 347
   }
  },
  {
   "name": "Pollution Liability Insurance Prog",
   "fy2022": 5186581.96,
   "fy2023": 1458728.57,
   "delta": -3727853.39,
   "pct": -71.9,
   "rows": {
    "2022": 437,
    "2023": 461
   }
  },
  {
   "name": "Volunteer Firefighters",
   "fy2022": 281502.87,
   "fy2023": 1413503.71,
   "delta": 1132000.84,
   "pct": 402.1,
   "rows": {
    "2022": 285,
    "2023": 308
   }
  },
  {
   "name": "Human Rights Commission",
   "fy2022": 991962.42,
   "fy2023": 1396050.2,
   "delta": 404087.78,
   "pct": 40.7,
   "rows": {
    "2022": 346,
    "2023": 379
   }
  },
  {
   "name": "Accountancy",
   "fy2022": 951302.43,
   "fy2023": 1341334.09,
   "delta": 390031.66,
   "pct": 41.0,
   "rows": {
    "2022": 345,
    "2023": 394
   }
  },
  {
   "name": "Environ & Land Use Hearings Office",
   "fy2022": 1086806.28,
   "fy2023": 1315793.74,
   "delta": 228987.46,
   "pct": 21.1,
   "rows": {
    "2022": 362,
    "2023": 387
   }
  },
  {
   "name": "Supreme Court",
   "fy2022": 955120.63,
   "fy2023": 1290314.58,
   "delta": 335193.95,
   "pct": 35.1,
   "rows": {
    "2022": 296,
    "2023": 432
   }
  },
  {
   "name": "Public Employment Relations Cmsn",
   "fy2022": 975784.56,
   "fy2023": 1221796.66,
   "delta": 246012.1,
   "pct": 25.2,
   "rows": {
    "2022": 393,
    "2023": 477
   }
  },
  {
   "name": "Horse Racing Commission",
   "fy2022": 1138528.91,
   "fy2023": 1099298.75,
   "delta": -39230.16,
   "pct": -3.4,
   "rows": {
    "2022": 579,
    "2023": 587
   }
  },
  {
   "name": "Bd of Reg Prof Eng & Land Surveyors",
   "fy2022": 940059.02,
   "fy2023": 1089284.44,
   "delta": 149225.42,
   "pct": 15.9,
   "rows": {
    "2022": 367,
    "2023": 493
   }
  },
  {
   "name": "Actuary",
   "fy2022": 1099713.94,
   "fy2023": 1053295.77,
   "delta": -46418.17,
   "pct": -4.2,
   "rows": {
    "2022": 246,
    "2023": 260
   }
  },
  {
   "name": "Office of Legislative Support Svcs",
   "fy2022": 1031138.7,
   "fy2023": 1038171.15,
   "delta": 7032.45,
   "pct": 0.7,
   "rows": {
    "2022": 644,
    "2023": 752
   }
  },
  {
   "name": "Law Library",
   "fy2022": 980250.51,
   "fy2023": 1030804.88,
   "delta": 50554.37,
   "pct": 5.2,
   "rows": {
    "2022": 330,
    "2023": 342
   }
  },
  {
   "name": "Lieutenant Governor",
   "fy2022": 947874.09,
   "fy2023": 644118.88,
   "delta": -303755.21,
   "pct": -32.0,
   "rows": {
    "2022": 273,
    "2023": 320
   }
  },
  {
   "name": "Tax Appeals",
   "fy2022": 639172.27,
   "fy2023": 624120.52,
   "delta": -15051.75,
   "pct": -2.4,
   "rows": {
    "2022": 270,
    "2023": 273
   }
  },
  {
   "name": "African American Affairs",
   "fy2022": 120038.11,
   "fy2023": 612926.3,
   "delta": 492888.19,
   "pct": 410.6,
   "rows": {
    "2022": 218,
    "2023": 285
   }
  },
  {
   "name": "Caseload Forecast Council",
   "fy2022": 536423.67,
   "fy2023": 556973.18,
   "delta": 20549.51,
   "pct": 3.8,
   "rows": {
    "2022": 233,
    "2023": 228
   }
  },
  {
   "name": "LEOFF 2 Retirement Board",
   "fy2022": 539257.4,
   "fy2023": 531961.14,
   "delta": -7296.26,
   "pct": -1.4,
   "rows": {
    "2022": 350,
    "2023": 362
   }
  },
  {
   "name": "Statute Law Committee",
   "fy2022": 496958.37,
   "fy2023": 483795.67,
   "delta": -13162.7,
   "pct": -2.6,
   "rows": {
    "2022": 319,
    "2023": 355
   }
  },
  {
   "name": "Columbia River Gorge Commission",
   "fy2022": 316444.83,
   "fy2023": 415071.48,
   "delta": 98626.65,
   "pct": 31.2,
   "rows": {
    "2022": 267,
    "2023": 322
   }
  },
  {
   "name": "LEAP Committee",
   "fy2022": 385015.94,
   "fy2023": 370471.14,
   "delta": -14544.8,
   "pct": -3.8,
   "rows": {
    "2022": 206,
    "2023": 189
   }
  },
  {
   "name": "Judicial Conduct",
   "fy2022": 369827.78,
   "fy2023": 278942.38,
   "delta": -90885.4,
   "pct": -24.6,
   "rows": {
    "2022": 191,
    "2023": 208
   }
  },
  {
   "name": "Indian Affairs",
   "fy2022": 186294.05,
   "fy2023": 251776.56,
   "delta": 65482.51,
   "pct": 35.2,
   "rows": {
    "2022": 235,
    "2023": 286
   }
  },
  {
   "name": "Forensic Investigations Council",
   "fy2022": 337386.87,
   "fy2023": 251104.85,
   "delta": -86282.02,
   "pct": -25.6,
   "rows": {
    "2022": 43,
    "2023": 34
   }
  },
  {
   "name": "Washington State Leadership Board",
   "fy2022": 0.0,
   "fy2023": 209777.13,
   "delta": 209777.13,
   "pct": null,
   "rows": {
    "2022": 0,
    "2023": 106
   }
  },
  {
   "name": "Asian Pacific American Affairs",
   "fy2022": 179859.09,
   "fy2023": 201041.07,
   "delta": 21181.98,
   "pct": 11.8,
   "rows": {
    "2022": 242,
    "2023": 382
   }
  },
  {
   "name": "Hispanic Affairs",
   "fy2022": 182225.86,
   "fy2023": 172382.04,
   "delta": -9843.82,
   "pct": -5.4,
   "rows": {
    "2022": 266,
    "2023": 307
   }
  },
  {
   "name": "Economic & Revenue Forecast Council",
   "fy2022": 123559.17,
   "fy2023": 137719.91,
   "delta": 14160.74,
   "pct": 11.5,
   "rows": {
    "2022": 193,
    "2023": 206
   }
  },
  {
   "name": "Redistricting Commission",
   "fy2022": 881126.09,
   "fy2023": 109332.05,
   "delta": -771794.04,
   "pct": -87.6,
   "rows": {
    "2022": 195,
    "2023": 17
   }
  },
  {
   "name": "Salaries for Elected Officials",
   "fy2022": 80951.34,
   "fy2023": 109289.72,
   "delta": 28338.38,
   "pct": 35.0,
   "rows": {
    "2022": 184,
    "2023": 314
   }
  },
  {
   "name": "State Legislative Labor Relations",
   "fy2022": 0.0,
   "fy2023": 34643.05,
   "delta": 34643.05,
   "pct": null,
   "rows": {
    "2022": 0,
    "2023": 28
   }
  },
  {
   "name": "Sundry Claims",
   "fy2022": 134759.0,
   "fy2023": 0.0,
   "delta": -134759.0,
   "pct": -100.0,
   "rows": {
    "2022": 8,
    "2023": 0
   }
  }
 ],
 "categories": [
  {
   "name": "Grants, Benefits & Client Services",
   "fy2022": 23309633530.62,
   "fy2023": 26601507431.54,
   "delta": 3291873900.92
  },
  {
   "name": "Goods and Services",
   "fy2022": 3698881382.0,
   "fy2023": 3656396131.85,
   "delta": -42485250.15
  },
  {
   "name": "Capital Outlays",
   "fy2022": 1570419145.35,
   "fy2023": 2119738471.7,
   "delta": 549319326.35
  },
  {
   "name": "Personal Service Contracts",
   "fy2022": 836509512.15,
   "fy2023": 1193988309.66,
   "delta": 357478797.51
  },
  {
   "name": "Travel",
   "fy2022": 59654627.3,
   "fy2023": 94020614.46,
   "delta": 34365987.16
  },
  {
   "name": "Debt Service",
   "fy2022": 23124247.04,
   "fy2023": 23519276.88,
   "delta": 395029.84
  },
  {
   "name": "Cost Of Goods Sold",
   "fy2022": 12141307.16,
   "fy2023": 11323172.45,
   "delta": -818134.71
  },
  {
   "name": "Intra-Agency Reimbursements",
   "fy2022": 11004307.95,
   "fy2023": 9950440.73,
   "delta": -1053867.22
  },
  {
   "name": "Interagency Reimbursements",
   "fy2022": 14001400.08,
   "fy2023": 1368602.11,
   "delta": -12632797.97
  }
 ],
 "topVendors": [
  {
   "name": "Molina Healthcare Of Washington",
   "total": 5253560582.89,
   "payments": 12,
   "topAgencies": [
    "Health Care Authority"
   ],
   "sampleRows": [
    {
     "sheet": "FY 2023",
     "month": 12,
     "agency": "Health Care Authority",
     "subcategory": "Direct Payments to Providers",
     "amount": 795347669.46
    },
    {
     "sheet": "FY 2023",
     "month": 6,
     "agency": "Health Care Authority",
     "subcategory": "Direct Payments to Providers",
     "amount": 778995466.16
    },
    {
     "sheet": "FY 2023",
     "month": 3,
     "agency": "Health Care Authority",
     "subcategory": "Direct Payments to Providers",
     "amount": 761392757.64
    }
   ]
  },
  {
   "name": "Consumer Direct Care Network Was",
   "total": 2056859042.48,
   "payments": 12,
   "topAgencies": [
    "Social and Health Services"
   ],
   "sampleRows": [
    {
     "sheet": "FY 2023",
     "month": 6,
     "agency": "Social and Health Services",
     "subcategory": "Direct Payments to Providers",
     "amount": 212025983.4
    },
    {
     "sheet": "FY 2023",
     "month": 9,
     "agency": "Social and Health Services",
     "subcategory": "Direct Payments to Providers",
     "amount": 206193145.14
    },
    {
     "sheet": "FY 2023",
     "month": 12,
     "agency": "Social and Health Services",
     "subcategory": "Direct Payments to Providers",
     "amount": 200017517.74
    }
   ]
  },
  {
   "name": "United Health Care Of Washington",
   "total": 1443531310.26,
   "payments": 12,
   "topAgencies": [
    "Health Care Authority"
   ],
   "sampleRows": [
    {
     "sheet": "FY 2023",
     "month": 6,
     "agency": "Health Care Authority",
     "subcategory": "Direct Payments to Providers",
     "amount": 225435838.33
    },
    {
     "sheet": "FY 2023",
     "month": 3,
     "agency": "Health Care Authority",
     "subcategory": "Direct Payments to Providers",
     "amount": 220606196.13
    },
    {
     "sheet": "FY 2023",
     "month": 1,
     "agency": "Health Care Authority",
     "subcategory": "Direct Payments to Providers",
     "amount": 215293282.94
    }
   ]
  },
  {
   "name": "Amerigroup Washington Inc",
   "total": 1435296723.21,
   "payments": 22,
   "topAgencies": [
    "Health Care Authority"
   ],
   "sampleRows": [
    {
     "sheet": "FY 2023",
     "month": 3,
     "agency": "Health Care Authority",
     "subcategory": "Direct Payments to Providers",
     "amount": 221403666.3
    },
    {
     "sheet": "FY 2023",
     "month": 1,
     "agency": "Health Care Authority",
     "subcategory": "Direct Payments to Providers",
     "amount": 215390126.12
    },
    {
     "sheet": "FY 2023",
     "month": 6,
     "agency": "Health Care Authority",
     "subcategory": "Direct Payments to Providers",
     "amount": 210701710.29
    }
   ]
  },
  {
   "name": "Community Health Plan Of Washing",
   "total": 1346547804.19,
   "payments": 12,
   "topAgencies": [
    "Health Care Authority"
   ],
   "sampleRows": [
    {
     "sheet": "FY 2023",
     "month": 6,
     "agency": "Health Care Authority",
     "subcategory": "Direct Payments to Providers",
     "amount": 213394104.68
    },
    {
     "sheet": "FY 2023",
     "month": 3,
     "agency": "Health Care Authority",
     "subcategory": "Direct Payments to Providers",
     "amount": 206167061.09
    },
    {
     "sheet": "FY 2023",
     "month": 1,
     "agency": "Health Care Authority",
     "subcategory": "Direct Payments to Providers",
     "amount": 195426174.58
    }
   ]
  },
  {
   "name": "Coordinated Care Of Washington I",
   "total": 1169634977.54,
   "payments": 12,
   "topAgencies": [
    "Health Care Authority"
   ],
   "sampleRows": [
    {
     "sheet": "FY 2023",
     "month": 6,
     "agency": "Health Care Authority",
     "subcategory": "Direct Payments to Providers",
     "amount": 184478805.53
    },
    {
     "sheet": "FY 2023",
     "month": 3,
     "agency": "Health Care Authority",
     "subcategory": "Direct Payments to Providers",
     "amount": 177056659.9
    },
    {
     "sheet": "FY 2023",
     "month": 1,
     "agency": "Health Care Authority",
     "subcategory": "Direct Payments to Providers",
     "amount": 172087415.96
    }
   ]
  },
  {
   "name": "Geocko Inc",
   "total": 462706087.08,
   "payments": 27,
   "topAgencies": [
    "Commerce",
    "Social and Health Services",
    "Agriculture"
   ],
   "sampleRows": [
    {
     "sheet": "FY 2023",
     "month": 7,
     "agency": "Social and Health Services",
     "subcategory": "Direct Payments to Providers",
     "amount": 315647076.92
    },
    {
     "sheet": "FY 2023",
     "month": 12,
     "agency": "Commerce",
     "subcategory": "Management/Organizational Services",
     "amount": 83822918.9
    },
    {
     "sheet": "FY 2023",
     "month": 6,
     "agency": "Commerce",
     "subcategory": "Other Grants/Benefits/Client Svcs",
     "amount": 15294946.67
    }
   ]
  },
  {
   "name": "Dcyf",
   "total": 309994315.04,
   "payments": 138,
   "topAgencies": [
    "Social and Health Services",
    "Children, Youth, and Families",
    "Health"
   ],
   "sampleRows": [
    {
     "sheet": "FY 2023",
     "month": 3,
     "agency": "Social and Health Services",
     "subcategory": "Direct Payments to Providers",
     "amount": 88419249.89
    },
    {
     "sheet": "FY 2023",
     "month": 4,
     "agency": "Social and Health Services",
     "subcategory": "Direct Payments to Providers",
     "amount": 56013984.76
    },
    {
     "sheet": "FY 2023",
     "month": 12,
     "agency": "Social and Health Services",
     "subcategory": "Direct Payments to Providers",
     "amount": 55372129.02
    }
   ]
  },
  {
   "name": "Us Bank Purchasing Card Program",
   "total": 266384717.8,
   "payments": 7819,
   "topAgencies": [
    "Social and Health Services",
    "Natural Resources",
    "Children, Youth, and Families"
   ],
   "sampleRows": [
    {
     "sheet": "FY 2023",
     "month": 12,
     "agency": "Transportation",
     "subcategory": "Other Goods and Services",
     "amount": 8972272.02
    },
    {
     "sheet": "FY 2023",
     "month": 10,
     "agency": "Transportation",
     "subcategory": "Other Goods and Services",
     "amount": 8529970.33
    },
    {
     "sheet": "FY 2023",
     "month": 11,
     "agency": "Transportation",
     "subcategory": "Other Goods and Services",
     "amount": 6637665.88
    }
   ]
  },
  {
   "name": "Clark Construction Llc",
   "total": 256244851.66,
   "payments": 13,
   "topAgencies": [
    "Transportation"
   ],
   "sampleRows": [
    {
     "sheet": "FY 2023",
     "month": 5,
     "agency": "Transportation",
     "subcategory": "Highway Construction",
     "amount": 42533553.88
    },
    {
     "sheet": "FY 2023",
     "month": 9,
     "agency": "Transportation",
     "subcategory": "Highway Construction",
     "amount": 32945542.55
    },
    {
     "sheet": "FY 2023",
     "month": 4,
     "agency": "Transportation",
     "subcategory": "Highway Construction",
     "amount": 27855228.78
    }
   ]
  },
  {
   "name": "Public Consulting Group Inc",
   "total": 219986523.89,
   "payments": 51,
   "topAgencies": [
    "Social and Health Services",
    "Health Care Authority",
    "Corrections"
   ],
   "sampleRows": [
    {
     "sheet": "FY 2023",
     "month": 12,
     "agency": "Health Care Authority",
     "subcategory": "Other Contractual Services",
     "amount": 148468054.94
    },
    {
     "sheet": "FY 2023",
     "month": 6,
     "agency": "Health Care Authority",
     "subcategory": "Other Contractual Services",
     "amount": 61796704.72
    },
    {
     "sheet": "FY 2023",
     "month": 11,
     "agency": "Social and Health Services",
     "subcategory": "Other Professional Services",
     "amount": 2727233.0
    }
   ]
  },
  {
   "name": "Molina Healthcare Of Wa Inc",
   "total": 214478687.09,
   "payments": 24,
   "topAgencies": [
    "Health Care Authority",
    "Social and Health Services"
   ],
   "sampleRows": [
    {
     "sheet": "FY 2023",
     "month": 3,
     "agency": "Health Care Authority",
     "subcategory": "Direct Payments to Providers",
     "amount": 33847421.41
    },
    {
     "sheet": "FY 2023",
     "month": 7,
     "agency": "Health Care Authority",
     "subcategory": "Direct Payments to Providers",
     "amount": 31364961.35
    },
    {
     "sheet": "FY 2023",
     "month": 1,
     "agency": "Health Care Authority",
     "subcategory": "Direct Payments to Providers",
     "amount": 28819419.33
    }
   ]
  },
  {
   "name": "Harborview Medical Center",
   "total": 180416725.51,
   "payments": 102,
   "topAgencies": [
    "Labor and Industries",
    "Health",
    "Health Care Authority"
   ],
   "sampleRows": [
    {
     "sheet": "FY 2023",
     "month": 9,
     "agency": "Health Care Authority",
     "subcategory": "Direct Payments to Providers",
     "amount": 28928076.01
    },
    {
     "sheet": "FY 2023",
     "month": 12,
     "agency": "Health Care Authority",
     "subcategory": "Direct Payments to Providers",
     "amount": 17628979.31
    },
    {
     "sheet": "FY 2023",
     "month": 1,
     "agency": "Health Care Authority",
     "subcategory": "Direct Payments to Providers",
     "amount": 14455256.25
    }
   ]
  },
  {
   "name": "Atg Legal Svcs",
   "total": 156563768.43,
   "payments": 792,
   "topAgencies": [
    "Revenue",
    "State Patrol",
    "Transportation"
   ],
   "sampleRows": [
    {
     "sheet": "FY 2023",
     "month": 4,
     "agency": "Children, Youth, and Families",
     "subcategory": "Attorney General Services",
     "amount": 8083898.05
    },
    {
     "sheet": "FY 2023",
     "month": 1,
     "agency": "Children, Youth, and Families",
     "subcategory": "Attorney General Services",
     "amount": 7333240.44
    },
    {
     "sheet": "FY 2023",
     "month": 4,
     "agency": "Labor and Industries",
     "subcategory": "Attorney General Services",
     "amount": 4956229.45
    }
   ]
  },
  {
   "name": "Res-Care Of Washington Inc.",
   "total": 154305887.1,
   "payments": 12,
   "topAgencies": [
    "Social and Health Services"
   ],
   "sampleRows": [
    {
     "sheet": "FY 2023",
     "month": 3,
     "agency": "Social and Health Services",
     "subcategory": "Direct Payments to Providers",
     "amount": 13498392.03
    },
    {
     "sheet": "FY 2023",
     "month": 12,
     "agency": "Social and Health Services",
     "subcategory": "Direct Payments to Providers",
     "amount": 13334076.03
    },
    {
     "sheet": "FY 2023",
     "month": 10,
     "agency": "Social and Health Services",
     "subcategory": "Direct Payments to Providers",
     "amount": 13185547.93
    }
   ]
  }
 ],
 "concentration": {
  "top10Share": 41.5,
  "top100Share": 59.2,
  "vendorCount": 78061
 },
 "monthly": {
  "2022": [
   3446473054.66,
   1511666571.93,
   3168150366.09,
   2327239782.44,
   1589116217.55,
   3155895567.73,
   2500740123.95,
   2379785813.64,
   2577922072.74,
   2399425020.01,
   2468839253.93,
   2010115614.98
  ],
  "2023": [
   3431543877.7,
   1916108451.93,
   3589221861.53,
   2643727476.89,
   1901393760.1,
   3655294602.3,
   3028810436.86,
   2497958921.13,
   2807053314.59,
   2524977449.51,
   1978473812.75,
   3737248486.09
  ]
 },
 "meta": {
  "sourceFile": "Vendor-Payments_2021-23.xlsx",
  "totalRows": 935853,
  "sheets": {
   "FY 2022": 451029,
   "FY 2023": 484824
  },
  "agencyCount": 102,
  "vendorCount": 97519,
  "generated": "deterministic pipeline v1 \u2014 no model involvement in any figure"
 }
} as const;
